### ISSUE TITLE
before running python ./example_3Dmorphing.py -- change the gpu id

### ISSUE THREAD

**Issue by TheMich01** [XiaokunSun/MorphAny3D#2]
I'm using ubuntu 22 and 24, my env use cuda 12.1 and torch 2.5.1, i had a very hard time to setup the env but it works, my problem now is that i can't finish the inference because i have not enough space on my hard dirve, but 'ill solve it, anyway to run the inference you must changhe the gpu id because in the example_3Dmorphing.py the gpu is set as:
os.environ["CUDA_VISIBLE_DEVICES"] = "7"
and has to be changed in
os.environ["CUDA_VISIBLE_DEVICES"] = "0"
if you do not change the id the gpu is not detected.
As soon as i'll expand my hard disk space i'll test again the tool.
I thing this morph can be a real game change in 3d computer graphics.
Thank's for release the code.
Bye
Mich

**Comment by XiaokunSun** [comment]
I'm glad our work was helpful. I've fixed the script bug. Because key-value features need to be cached during the transformation process, we recommend keeping at least 30GB of disk space. Please feel free to contact me if you have any questions!
